// <auto-generated />
using LooseEnds.Api.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LooseEnds.Api.Migrations;

[DbContext(typeof(GameContext))]
[Migration("20250330214800_InitialCreate")]
partial class InitialCreate
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

        modelBuilder.Entity("LooseEndsApi.Data.Models.GameSession", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<string>("GameCode")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<bool>("HasStarted")
                    .HasColumnType("INTEGER");

                b.HasKey("Id");

                b.ToTable("GameSessions");
            });

        modelBuilder.Entity("LooseEndsApi.Data.Models.Player", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<int>("GameSessionId")
                    .HasColumnType("INTEGER");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("GameSessionId");

                b.ToTable("Players");
            });

        modelBuilder.Entity("LooseEndsApi.Data.Models.Player", b =>
            {
                b.HasOne("LooseEndsApi.Data.Models.GameSession", "GameSession")
                    .WithMany("Players")
                    .HasForeignKey("GameSessionId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("GameSession");
            });

        modelBuilder.Entity("LooseEndsApi.Data.Models.GameSession", b =>
            {
                b.Navigation("Players");
            });
#pragma warning restore 612, 618
    }
}
