// <auto-generated />
using System;
using LooseEnds.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LooseEnds.Api.Migrations;

[DbContext(typeof(GameContext))]
[Migration("20250503232758_Test")]
partial class Test
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

        modelBuilder.Entity("LooseEndsApi.Data.Models.DefaultResponse", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<string>("Content")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.ToTable("DefaultResponses");
            });

        modelBuilder.Entity("LooseEndsApi.Data.Models.GameSession", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<DateTime>("DateCreatedUtc")
                    .HasColumnType("TEXT");

                b.Property<string>("GameCode")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<bool>("InLobby")
                    .HasColumnType("INTEGER");

                b.Property<bool>("IsCompleted")
                    .HasColumnType("INTEGER");

                b.Property<bool>("IsStarted")
                    .HasColumnType("INTEGER");

                b.HasKey("Id");

                b.ToTable("GameSessions");
            });

        modelBuilder.Entity("LooseEndsApi.Data.Models.Player", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<int>("GameSessionId")
                    .HasColumnType("INTEGER");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<int>("Points")
                    .HasColumnType("INTEGER");

                b.HasKey("Id");

                b.HasIndex("GameSessionId");

                b.ToTable("Players");
            });

        modelBuilder.Entity("LooseEndsApi.Data.Models.PlayerResponse", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<string>("Answer")
                    .HasColumnType("TEXT");

                b.Property<int>("PlayerId")
                    .HasColumnType("INTEGER");

                b.Property<int>("RoundPromptId")
                    .HasColumnType("INTEGER");

                b.Property<int>("Votes")
                    .HasColumnType("INTEGER");

                b.HasKey("Id");

                b.HasIndex("PlayerId");

                b.HasIndex("RoundPromptId");

                b.ToTable("PlayerResponses");
            });

        modelBuilder.Entity("LooseEndsApi.Data.Models.Prompt", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<bool>("Active")
                    .HasColumnType("INTEGER");

                b.Property<string>("Content")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.ToTable("Prompts");
            });

        modelBuilder.Entity("LooseEndsApi.Data.Models.Round", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<int>("GameSessionId")
                    .HasColumnType("INTEGER");

                b.Property<bool>("IsCompleted")
                    .HasColumnType("INTEGER");

                b.HasKey("Id");

                b.HasIndex("GameSessionId");

                b.ToTable("Rounds");
            });

        modelBuilder.Entity("LooseEndsApi.Data.Models.RoundPrompt", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<int>("PromptId")
                    .HasColumnType("INTEGER");

                b.Property<int>("RoundId")
                    .HasColumnType("INTEGER");

                b.HasKey("Id");

                b.HasIndex("PromptId");

                b.HasIndex("RoundId");

                b.ToTable("RoundPrompts");
            });

        modelBuilder.Entity("LooseEndsApi.Data.Models.Player", b =>
            {
                b.HasOne("LooseEndsApi.Data.Models.GameSession", "GameSession")
                    .WithMany("Players")
                    .HasForeignKey("GameSessionId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("GameSession");
            });

        modelBuilder.Entity("LooseEndsApi.Data.Models.PlayerResponse", b =>
            {
                b.HasOne("LooseEndsApi.Data.Models.Player", "Player")
                    .WithMany()
                    .HasForeignKey("PlayerId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("LooseEndsApi.Data.Models.RoundPrompt", "RoundPrompt")
                    .WithMany("PlayerResponses")
                    .HasForeignKey("RoundPromptId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Player");

                b.Navigation("RoundPrompt");
            });

        modelBuilder.Entity("LooseEndsApi.Data.Models.Round", b =>
            {
                b.HasOne("LooseEndsApi.Data.Models.GameSession", "GameSession")
                    .WithMany("Rounds")
                    .HasForeignKey("GameSessionId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("GameSession");
            });

        modelBuilder.Entity("LooseEndsApi.Data.Models.RoundPrompt", b =>
            {
                b.HasOne("LooseEndsApi.Data.Models.Prompt", "Prompt")
                    .WithMany("RoundPrompts")
                    .HasForeignKey("PromptId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("LooseEndsApi.Data.Models.Round", "Round")
                    .WithMany("RoundPrompts")
                    .HasForeignKey("RoundId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Prompt");

                b.Navigation("Round");
            });

        modelBuilder.Entity("LooseEndsApi.Data.Models.GameSession", b =>
            {
                b.Navigation("Players");

                b.Navigation("Rounds");
            });

        modelBuilder.Entity("LooseEndsApi.Data.Models.Prompt", b =>
            {
                b.Navigation("RoundPrompts");
            });

        modelBuilder.Entity("LooseEndsApi.Data.Models.Round", b =>
            {
                b.Navigation("RoundPrompts");
            });

        modelBuilder.Entity("LooseEndsApi.Data.Models.RoundPrompt", b =>
            {
                b.Navigation("PlayerResponses");
            });
#pragma warning restore 612, 618
    }
}
