// <auto-generated />
using System;
using LooseEnds.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LooseEnds.Database.Migrations
{
    [DbContext(typeof(GameContext))]
    [Migration("20260225022108_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("LooseEnds.Database.Entities.DefaultResponse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DefaultResponses");
                });

            modelBuilder.Entity("LooseEnds.Database.Entities.GameSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateCreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("GameCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HostId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("RoundTimer")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("GameSessions");
                });

            modelBuilder.Entity("LooseEnds.Database.Entities.Player", b =>
                {
                    b.Property<string>("PlayerId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsBot")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SessionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PlayerId");

                    b.HasIndex("SessionId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("LooseEnds.Database.Entities.PlayerResponse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Answer")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlayerId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PromptId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("SubmittedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("PromptId");

                    b.ToTable("PlayerResponses");
                });

            modelBuilder.Entity("LooseEnds.Database.Entities.PlayerVote", b =>
                {
                    b.Property<string>("PlayerId")
                        .HasColumnType("TEXT");

                    b.Property<int>("ResponseId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PlayerId", "ResponseId");

                    b.HasIndex("ResponseId");

                    b.ToTable("PlayerVotes");
                });

            modelBuilder.Entity("LooseEnds.Database.Entities.Prompt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Prompts");
                });

            modelBuilder.Entity("LooseEnds.Database.Entities.Round", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("AnswerDueUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PromptingCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SessionId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("VotingCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("VotingRoundPromptId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.HasIndex("VotingRoundPromptId");

                    b.ToTable("Rounds");
                });

            modelBuilder.Entity("LooseEnds.Database.Entities.RoundPrompt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RoundId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("VoteDueUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoundId");

                    b.ToTable("RoundPrompts");
                });

            modelBuilder.Entity("LooseEnds.Database.Entities.Player", b =>
                {
                    b.HasOne("LooseEnds.Database.Entities.GameSession", "Session")
                        .WithMany("Players")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("LooseEnds.Database.Entities.PlayerResponse", b =>
                {
                    b.HasOne("LooseEnds.Database.Entities.Player", "Player")
                        .WithMany("Responses")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LooseEnds.Database.Entities.RoundPrompt", "Prompt")
                        .WithMany("PlayerResponses")
                        .HasForeignKey("PromptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Prompt");
                });

            modelBuilder.Entity("LooseEnds.Database.Entities.PlayerVote", b =>
                {
                    b.HasOne("LooseEnds.Database.Entities.Player", "Player")
                        .WithMany("Votes")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LooseEnds.Database.Entities.PlayerResponse", "Response")
                        .WithMany("Votes")
                        .HasForeignKey("ResponseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Response");
                });

            modelBuilder.Entity("LooseEnds.Database.Entities.Round", b =>
                {
                    b.HasOne("LooseEnds.Database.Entities.GameSession", "Session")
                        .WithMany("Rounds")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LooseEnds.Database.Entities.RoundPrompt", "VotingRoundPrompt")
                        .WithMany()
                        .HasForeignKey("VotingRoundPromptId");

                    b.Navigation("Session");

                    b.Navigation("VotingRoundPrompt");
                });

            modelBuilder.Entity("LooseEnds.Database.Entities.RoundPrompt", b =>
                {
                    b.HasOne("LooseEnds.Database.Entities.Round", "Round")
                        .WithMany("RoundPrompts")
                        .HasForeignKey("RoundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Round");
                });

            modelBuilder.Entity("LooseEnds.Database.Entities.GameSession", b =>
                {
                    b.Navigation("Players");

                    b.Navigation("Rounds");
                });

            modelBuilder.Entity("LooseEnds.Database.Entities.Player", b =>
                {
                    b.Navigation("Responses");

                    b.Navigation("Votes");
                });

            modelBuilder.Entity("LooseEnds.Database.Entities.PlayerResponse", b =>
                {
                    b.Navigation("Votes");
                });

            modelBuilder.Entity("LooseEnds.Database.Entities.Round", b =>
                {
                    b.Navigation("RoundPrompts");
                });

            modelBuilder.Entity("LooseEnds.Database.Entities.RoundPrompt", b =>
                {
                    b.Navigation("PlayerResponses");
                });
#pragma warning restore 612, 618
        }
    }
}
